$OFS = "`r`n"
$scriptname = "win11deb.ps1"


if (Test-Path -Path "$($scriptname)")
{
    Remove-Item -Force "$($scriptname)"
}

Write-output '
################################################################################################################
###                                                                                                          ###
### WARNING: This file is automatically generated DO NOT modify this file directly as it will be overwritten ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

# Script-level param block MUST come before any other executable code
Write-output '
param (
    [switch]$SmokeTest,
    [string]$Config
)

#requires -Version 7.0
Set-StrictMode -Version Latest
' | Out-File ./$scriptname -Append -Encoding UTF8

# Get-Content .\scripts\start.ps1 | Out-File ./$scriptname -Append -Encoding UTF8
# Get-Content .\scripts\main.ps1 | Out-File ./$scriptname -Append -Encoding UTF8

Write-output '
################################################################################################################
###                                                                                                          ###
###                                         INFO: JSON CONFIGS                                               ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\config\applications.json | ForEach-Object {
    $jsonObject = (Get-Content $_.FullName) -join "`n" | ConvertFrom-Json

    $convertedArray = $jsonObject | ForEach-Object {
        $objString = @{
            'id'    = $_.id
            'name'  = $_.name
            'winget'= $_.winget
        } | ConvertTo-Json -Compress
        "'$objString'"
    }

    $convertedArrayString = "@(" + ($convertedArray -join ',' ) + ")"

    Write-Output "`$programs = $convertedArrayString" | Out-File ./$scriptname -Append -Encoding UTF8
}

Get-ChildItem .\config\msAppxDebloat.json | ForEach-Object {
    $jsonObject = (Get-Content $_.FullName) -join "`n" | ConvertFrom-Json

    $convertedArray = $jsonObject | ForEach-Object {
        $objString = @{
            'id'    = $_.id
            'name'  = $_.name
        } | ConvertTo-Json -Compress
        "'$objString'"
    }

    $convertedArrayString = "@(" + ($convertedArray -join ',' ) + ")"

    Write-Output "`$appx = $convertedArrayString" | Out-File ./$scriptname -Append -Encoding UTF8
}

# ========================================
# Embed selected JSON files into variables
# ========================================

# Manually choose which JSON files you want
$jsonFiles = @(
    ".\config\tweaks.json",
    ".\config\preset.json",
    ".\config\feature.json",
    ".\config\configuration.json"
    # add more here...
)

# Pre-compile validation
$errors = @()
foreach ($file in $jsonFiles) {
    if (-not (Test-Path $file)) {
        $errors += "File not found: $file"
        continue
    }
    try {
        $null = Get-Content $file -Raw | ConvertFrom-Json
    } catch {
        $errors += "Invalid JSON in $file : $_"
    }
}
if ($errors.Count -gt 0) {
    Write-Error "Pre-compile validation failed:`n$($errors -join "`n")"
    exit 1
}

foreach ($file in $jsonFiles) {
    if (-not (Test-Path $file)) {
        Write-Warning "File not found: $file"
        continue
    }
    $varName = [System.IO.Path]::GetFileNameWithoutExtension($file)
    $jsonText = Get-Content $file -Raw
    $jsonText = $jsonText -replace "@'", "`@'"

    # Build PowerShell block
    $psContent = @"
# Embedded from $([System.IO.Path]::GetFileName($file))
`$$varName = @'
$jsonText
'@ | ConvertFrom-Json

"@
    $psContent | Out-File ./$scriptName -Append -Encoding UTF8
}

# Smoke test: validate configs and exit before loading any function files
Write-output '
if ($SmokeTest) {
    Write-Host "Running smoke test..." -ForegroundColor Cyan
    $errors = @()

    try {
        $null = $tweaks.PSObject.Properties.Name
        $tweakCount = ($tweaks.PSObject.Properties | Measure-Object).Count
        Write-Host "tweaks.json: OK ($tweakCount entries)" -ForegroundColor Green
    } catch {
        $errors += "tweaks.json validation failed: $_"
    }

    try {
        $null = $preset.PSObject.Properties.Name
        Write-Host "preset.json: OK" -ForegroundColor Green
    } catch {
        $errors += "preset.json validation failed: $_"
    }

    try {
        $null = $feature.PSObject.Properties.Name
        Write-Host "feature.json: OK" -ForegroundColor Green
    } catch {
        $errors += "feature.json validation failed: $_"
    }

    try {
        $null = $configuration.PSObject.Properties.Name
        Write-Host "configuration.json: OK" -ForegroundColor Green
    } catch {
        $errors += "configuration.json validation failed: $_"
    }

    try {
        $null = $programs.Count
        $programsCount = ($programs | Measure-Object).Count
        Write-Host "applications.json: OK ($programsCount entries)" -ForegroundColor Green
    } catch {
        $errors += "applications.json validation failed: $_"
    }

    try {
        $null = $appx.Count
        $appxCount = ($appx | Measure-Object).Count
        Write-Host "msAppxDebloat.json: OK ($appxCount entries)" -ForegroundColor Green
    } catch {
        $errors += "msAppxDebloat.json validation failed: $_"
    }

    if ($errors.Count -gt 0) {
        Write-Error "Smoke test failed with $($errors.Count) error(s):`n$($errors -join "`n")"
        exit 1
    }

    Write-Host "Smoke test passed. All configs are valid." -ForegroundColor Green
    exit 0
}
' | Out-File ./$scriptname -Append -Encoding UTF8

Write-output '
################################################################################################################
###                                                                                                          ###
###                                        INFO: MAIN FUNCTIONS                                            ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-Content .\scripts\start.ps1 | Out-File ./$scriptname -Append -Encoding UTF8
Get-Content .\scripts\main.ps1 | Out-File ./$scriptname -Append -Encoding UTF8

Write-output '
################################################################################################################
###                                                                                                          ###
###                                        INFO: HELPER FUNCTIONS                                            ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\functions\private\helper -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}

Write-output '
################################################################################################################
###                                                                                                          ###
###                                         INFO: INFO FUNCTIONS                                             ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\functions\public\info -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}

Write-output '
################################################################################################################
###                                                                                                          ###
###                                        INFO: INSTALL FUNCTIONS                                           ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\functions\private\installs -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}
Get-ChildItem .\functions\public\installs -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}

Write-output '
################################################################################################################
###                                                                                                          ###
###                                        INFO: DEBLOAT FUNCTIONS                                           ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\functions\private\debloat -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}
Get-ChildItem .\functions\public\debloat -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}

Write-output '
################################################################################################################
###                                                                                                          ###
###                                      INFO: OPTIMIZATION FUNCTIONS                                        ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\functions\private\optimization -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}
Get-ChildItem .\functions\public\optimization -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}

Write-output '
################################################################################################################
###                                                                                                          ###
###                                          INFO: UPDATES FUNCTIONS                                         ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\functions\public\updates -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}

Write-output '
################################################################################################################
###                                                                                                          ###
###                                           INFO: CONFIG FUNCTIONS                                         ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-ChildItem .\functions\private\config -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}
Get-ChildItem .\functions\public\config -Recurse -File | ForEach-Object {
    Get-Content $psitem.FullName | Out-File ./$scriptname -Append -Encoding UTF8
}

Write-output '
################################################################################################################
###                                                                                                          ###
###                                       INFO: SETUP BACKGROUND CONFIG                                      ###
###                                                                                                          ###
################################################################################################################
' | Out-File ./$scriptname -Append -Encoding UTF8

Get-Content .\scripts\closure.ps1 | Out-File ./$scriptname -Append -Encoding UTF8

